services:
  pipeline-db:
    image: postgres:16
    container_name: pipeline_postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"
    volumes:
      - pipeline_pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pipeline_pgdata: