version: '3.8'
services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: variant_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql